version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
     - "80:80"
    depends_on:
     - java-app
    networks:
     - java-network

  java-app:
    build:
      context: .
    container_name: "expensesapp"
    ports:
     - "8080:8080"
    environment:
     SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
     SPRING_DATASOURCE_USERNAME: "root"
     SPRING_DATASOURCE_PASSWORD: "Test@123"
    depends_on:
     - mysql
    restart: always
    networks:
     - java-network
    healthcheck:
     test: ["CMD-SHELL" , " curl -f http://loclhost:8080 || exit 1"]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 60s

  mysql:
    image: mysql
    container_name: "mysql"
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: "Test@123"
     MYSQL_DATABASE: "expenses_tracker"
    restart: always
    networks:
     - java-network
    volumes:
     - /opt/java-mysql/var/lib/mysql
    healthcheck:
     test: ["CMD" , "mysqladmin" , "ping" , "-h" , "localhost" , "-uroot" , "-pTest@123"]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 60s

networks:
  java-network:

